name: 'NativeIrisEventBinding'
description: 'Bindings to IrisEventHandler'

output: 'lib/src/native_iris_event_bindings.dart'

headers:
  entry-points:
    - 'ffigen_include/iris_event.h'
    
  include-directives:
    - 'ffigen_include/iris_event.h'

llvm-path:
  - '/usr/local/opt/llvm'

# Generating typedefs need set the sdk constraints to >=2.14, remove it 
# if we can set our sdk constraints to >=2.14
typedefs:
  exclude:
    - 'Dart_Port'

functions:
  symbol-address:
    include:
      - 'OnEvent' # Match function name.
      - 'OnEventEx' 