name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build_windows:
    name: Build Windows
    strategy:
      matrix:
        version: ['2.10.5', '3.0.0']
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
      - run: flutter pub get
      - name: Build windows
        run: flutter build windows
        working-directory: example

  build_ios:
    name: Build iOS
    strategy:
      matrix:
        version: ['2.10.5', '3.0.0']
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
      - run: flutter pub get
      - name: Run flutter build ios --no-codesign
        run: flutter build ios --no-codesign
        working-directory: example

  build_macos:
    name: Build macOS
    strategy:
      matrix:
        version: ['2.10.5', '3.0.0']
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
      - run: flutter pub get
      - name: Run flutter build macos
        run: flutter build macos
        working-directory: example

  build_android_windows:
    name: Build Android on Windows
    strategy:
      matrix:
        version: ['2.10.5', '3.0.0']
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
      - run: flutter pub get
      - name: Run flutter build apk
        run: flutter build apk
        working-directory: example

  build_android_ubuntu:
    name: Build Android on Ubuntu
    strategy:
      matrix:
        version: ['2.10.5', '3.0.0']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
      - run: flutter pub get
      - name: Run flutter build apk
        run: flutter build apk
        working-directory: example
