name: CI

on:
  push:
    branches: 
      - release/**
  pull_request:
    branches: 
      - main

jobs:
  cmake_build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Run cmake build android
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          ls $ANDROID_NDK
          bash ci/cmake-build-android.sh

      - name: Get current date
        id: date
        run: |
          VERSION=$(bash ci/grep_version.sh)
          DATE=$(date '+%Y%m%d')
          echo "::set-output name=date::$(echo '${VERSION}_${DATE}')"
      - name: Test with environment variables
        run: echo $BUILD_NAME
        env:
          BUILD_NAME: iris_event_${{ steps.date.outputs.date }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: iris_event_${{ steps.date.outputs.date }}
          files: "build/*.zip"

  cmake_build_ios:
    name: Build ios
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Run cmake build ios
        run: |
          bash ci/cmake-build-ios.sh
      - name: Get current date
        id: date
        run: |
          VERSION=$(bash ci/grep_version.sh)
          DATE=$(date '+%Y%m%d')
          echo "::set-output name=date::$(echo '${VERSION}_${DATE}')"
      - name: Test with environment variables
        run: echo $BUILD_NAME
        env:
          BUILD_NAME: iris_event_${{ steps.date.outputs.date }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: iris_event_${{ steps.date.outputs.date }}
          files: "build/*.zip"

  cmake_build_macos:
    name: Build macos
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Run cmake build macos
        run: |
          bash ci/cmake-build-macos.sh
      - name: Get current date
        id: date
        run: |
          VERSION=$(bash ci/grep_version.sh)
          DATE=$(date '+%Y%m%d')
          echo "::set-output name=date::$(echo '${VERSION}_${DATE}')"
      - name: Test with environment variables
        run: echo $BUILD_NAME
        env:
          BUILD_NAME: iris_event_${{ steps.date.outputs.date }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: iris_event_${{ steps.date.outputs.date }}
          files: "build/*.zip"

  cmake_build_windows:
    name: Build windows
    runs-on: windows-2019
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Run cmake build windows
        shell: bash
        run: |
          bash ci/cmake-build-windows.sh
      - name: Get current date
        id: date
        run: |
          VERSION=$(bash ci/grep_version.sh)
          DATE=$(date '+%Y%m%d')
          echo "::set-output name=date::$(echo '${VERSION}_${DATE}')"
      - name: Test with environment variables
        run: echo $BUILD_NAME
        env:
          BUILD_NAME: iris_event_${{ steps.date.outputs.date }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: iris_event_${{ steps.date.outputs.date }}
          files: "build/*.zip"
